[package]
name = "acmi-compress"
version = "0.1.0"
edition = "2021"

# Profiling!
[profile.dev]
opt-level = 2

[profile.release]
debug = true

[dependencies]
atty = "0.2.0"
anyhow = { version = "1.0", features = ["backtrace"] }
bytesize = "1.1"
camino = "1.0"
clap = { version = "3.0", features = ["derive"] }
float-ord = "0.3"
log = "0.4"
rustc-hash = "1.1"
simplelog = "0.12"
tacview = { git = "https://github.com/mrkline/tacview", rev = "314f3ad591aaaa92f703799b90a93b526a86f91d" }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
